services:
  cowrie:
    image: cowrie/cowrie
    volumes:
      - ./logs/ssh:/cowrie/cowrie-git/var/lib/cowrie/tty/
      - ./config/ssh/files:/cowrie/cowrie-git/var/lib/cowrie/downloads/
      - ./logs/ssh/cowrie.json:/cowrie/cowrie-git/var/log/cowrie/cowrie.json
      - ./logs/ssh/cowrie.log:/cowrie/cowrie-git/var/log/cowrie/cowrie.log
      - ./config/ssh/ssh_banner:/cowrie/cowrie-git/honeyfs/etc/motd
      - ./config/ssh:/var/lib/cowrie/tty
    ports:
      - 2222:2222 # Settare a 22 per ingannare attaccante (modificare un eventuale SSH per evitare conflitti)