services:
  ssh-honeypot:
    build: .
    ports:
      - "22:22"
    container_name: ssh_honeypot
    volumes:
      - ./config/ssh/users.txt:/etc/ssh/users.txt
      - ./config/ssh/sshd_config:/etc/ssh/sshd_config
      - ./config/ssh/ssh_banner:/etc/ssh/ssh_banner
    restart: always