services:
  ssh_vuln:
    build: .
    ports:
      - "2222:22"   # Mappa la porta 2222 dell'host alla porta 22 del container (SSH)
    container_name: ssh_vuln
    volumes:
      - ./config/ssh/banner.txt:/etc/ssh/banner.txt
      - ./logs:/var/log 
    restart: always
    networks:
      - honeynet

networks:
  honeynet:
    driver: bridge
